<a href="https://colab.research.google.com/github/ritam-sarkar/python_libraries/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
python_list = [1,2,3]
print(python_list, type(python_list))
arr1 = np.array([1,2,3])
print(arr1, type(arr1))


[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


#### Vectorized operation no lopp needed

In [4]:
# print with lambda
print("add 10 with each x on python list",[x+10 for x in python_list])
print("vectorized add",arr1+10)
print("add in list with numpy",np.add(python_list,10))


add 10 with each x on python list [11, 12, 13]
vectorized add [11 12 13]
add in list with numpy [11 12 13]


Other methods of numpy

In [5]:
print('print zeroes', np.zeros(3))
print('print ones for 3X2 dimension', np.ones((3,2)))
print('arrange 0 to 10 with gap of 2', np.arange(0,10,2))
print('random value between 2 to 3', np.random.rand(2,3))

print zeroes [0. 0. 0.]
print ones for 3X2 dimension [[1. 1.]
 [1. 1.]
 [1. 1.]]
arrange 0 to 10 with gap of 2 [0 2 4 6 8]
random value between 2 to 3 [[0.7038283  0.87895881 0.11692295]
 [0.18823208 0.00662201 0.50436802]]


Type promotion




int → float → complex → object

In [6]:
arr_int = np.array([1, 2, 3])
arr_float = np.array([1.0, 2.0, 3.0])
arr_mixed = np.array([1, 2.5, 3])  # Mixed types → promoted to float
arr_mixed2 = np.array([1, "hello", 3])
print('promoted to float ',arr_mixed)
print('promoted to string object ',arr_mixed2)

promoted to float  [1.  2.5 3. ]
promoted to string object  ['1' 'hello' '3']


n dimension array properties

In [21]:
arr = np.ones((2,3,4))
print(arr)
print('shape',arr.shape)
print('shape',arr.size)
print('itemsize ',arr.itemsize) # memory per element is 8 bytes
print('total memory used ', arr.nbytes)
print('dimension ', arr.ndim)
print('Transpose', arr.T.shape)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
shape (2, 3, 4)
shape 24
itemsize  8
total memory used  192
dimension  3
Transpose (4, 3, 2)


Indexing and slicing 1D

In [28]:
# 1D Array Indexing
print('--- 1D Array Indexing ---')
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70])
print(f'Original 1D array: {arr_1d}')

# Positive Indexing
print(f'Element at index 0: {arr_1d[0]}')
print(f'Element at index 3: {arr_1d[3]}')

# Negative Indexing
print(f'Element at last index (-1): {arr_1d[-1]}')
print(f'Element at second to last index (-2): {arr_1d[-2]}')

# Slicing (Positive Indices)
print(f'Elements from index 1 to 4 (exclusive): {arr_1d[1:4]}')
print(f'Elements from beginning to index 3 (exclusive): {arr_1d[:3]}')
print(f'Elements from index 4 to end: {arr_1d[4:]}')

# Slicing (Negative Indices)
print(f'Elements from beginning to second to last (exclusive): {arr_1d[:-1]}')
print(f'Elements from third to last to end: {arr_1d[-3:]}')

# Slicing (Mixed Positive/Negative Indices)
print(f'Elements from index 1 to second to last (exclusive): {arr_1d[1:-1]}')
print(f'Elements from index 2 to third to last (exclusive): {arr_1d[2:-2]}')

# slicing with step
print(f'Elements from index 1 to 4 (exclusive) with step 2: {arr_1d[1:4:2]}') #[start : end exclusive : step ]

--- 1D Array Indexing ---
Original 1D array: [10 20 30 40 50 60 70]
Element at index 0: 10
Element at index 3: 40
Element at last index (-1): 70
Element at second to last index (-2): 60
Elements from index 1 to 4 (exclusive): [20 30 40]
Elements from beginning to index 3 (exclusive): [10 20 30]
Elements from index 4 to end: [50 60 70]
Elements from beginning to second to last (exclusive): [10 20 30 40 50 60]
Elements from third to last to end: [50 60 70]
Elements from index 1 to second to last (exclusive): [20 30 40 50 60]
Elements from index 2 to third to last (exclusive): [30 40 50]
Elements from index 1 to 4 (exclusive) with step 2: [20 40]


Indexing and slicing 2D

In [32]:

# 2D Array Indexing
print('\n--- 2D Array Indexing ---')
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print('Original 2D array:\n', arr_2d)

# Positive Indexing (row, column)
print(f'Element at (0, 0): {arr_2d[0, 0]}')
print(f'Element at (1, 2): {arr_2d[1, 2]}')

# Negative Indexing
print(f'Element at last row, last column (-1, -1): {arr_2d[-1, -1]}')
print(f'Element at first row, second to last column (0, -2): {arr_2d[0, -2]}')

# Slicing Rows
print(f'First row: {arr_2d[0, :]}')
print(f'First two rows:\n{arr_2d[:2, :]}')
print(f'Last row: {arr_2d[-1, :]}')

# Slicing Columns
print(f'First column: {arr_2d[:, 0]}')
print(f'Last two columns:\n{arr_2d[:, -2:]}')

# Slicing Both Rows and Columns (Positive Indices)
print(f'Subset (top-left 2x2):\n{arr_2d[0:2, 0:2]}')

# Slicing Both Rows and Columns (Negative Indices)
print(f'Subset (bottom-right 2x2, using negative slicing):\n{arr_2d[-2:, -2:]}')

# Slicing Both Rows and Columns (Mixed Indices)
print(f'Subset (first row, last two columns): {arr_2d[0, -2:]}')
print(f'Subset (all rows, first to second to last column):\n{arr_2d[:, 0:-1]}')

# Using boolean indexing for more advanced selection
print('\n--- Boolean Indexing (2D Array) ---')
print(f'Elements greater than 7:\n{arr_2d[arr_2d > 7]}')
print(f'Elements which are even: {arr_2d[arr_2d % 2 == 0]}')
# Boolean element genration
print(f'Generate same shape but boolean value:\n  {arr_2d > 25}')


--- 2D Array Indexing ---
Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at (0, 0): 1
Element at (1, 2): 7
Element at last row, last column (-1, -1): 12
Element at first row, second to last column (0, -2): 3
First row: [1 2 3 4]
First two rows:
[[1 2 3 4]
 [5 6 7 8]]
Last row: [ 9 10 11 12]
First column: [1 5 9]
Last two columns:
[[ 3  4]
 [ 7  8]
 [11 12]]
Subset (top-left 2x2):
[[1 2]
 [5 6]]
Subset (bottom-right 2x2, using negative slicing):
[[ 7  8]
 [11 12]]
Subset (first row, last two columns): [3 4]
Subset (all rows, first to second to last column):
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

--- Boolean Indexing (2D Array) ---
Elements greater than 7:
[ 8  9 10 11 12]
Elements which are even: [ 2  4  6  8 10 12]
Generate same shape but boolean value:
  [[False False False False]
 [False False False False]
 [False False False False]]


Vector operation

Axis 0 = vertical direction (decrease rows for aggregation)

Axis 1 = horizontal direction (Decrease column for aggregation)

as it will become a 2D-1 = 1D array so the shapes are always like

sum on (2,3) axis = 0 shape = (3,)

sum on (2,3) axis = 1 shape = (2,)

In [43]:
# Vector operations on a 2D array
print('--- Vector Operations on 2D Array ---')

print('Original 2D array:\n', arr_2d)

# Addition with a scalar
print('\nAddition with scalar (5):\n', arr_2d + 5)

# Multiplication with a scalar
print('\nMultiplication with scalar (2):\n', arr_2d * 2)

# Subtraction with a scalar
print('\nSubtraction with scalar (3):\n', arr_2d - 3)

# Element-wise multiplication with another array (must have same shape)
arr_2d_b = np.array([[1, 1, 1, 1],
                     [2, 2, 2, 2],
                     [3, 3, 3, 3]])
print('\nElement-wise multiplication with another array (arr_2d_b):\n', arr_2d * arr_2d_b)

# Sum of all elements
print('\nSum of all elements:', np.sum(arr_2d))

# Sum along an axis (axis=0 for columns, axis=1 for rows)
print('\nSum along columns (axis=0):', np.sum(arr_2d, axis=0))
print('Sum along rows (axis=1):', np.sum(arr_2d, axis=1))

# Mean of all elements
print('\nMean of all elements:', np.mean(arr_2d))

# Mean along an axis
print('Mean along columns (axis=0):', np.mean(arr_2d, axis=0))
print('Mean along rows (axis=1):', np.mean(arr_2d, axis=1))

# Maximum element
print('\nMaximum element:', np.max(arr_2d))

# Maximum element along an axis
print('Maximum along columns (axis=0):', np.max(arr_2d, axis=0))
print('Maximum along rows (axis=1):', np.max(arr_2d, axis=1))

--- Vector Operations on 2D Array ---
Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Addition with scalar (5):
 [[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]

Multiplication with scalar (2):
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction with scalar (3):
 [[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]

Element-wise multiplication with another array (arr_2d_b):
 [[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]

Sum of all elements: 78

Sum along columns (axis=0): [15 18 21 24]
Sum along rows (axis=1): [10 26 42]

Mean of all elements: 6.5
Mean along columns (axis=0): [5. 6. 7. 8.]
Mean along rows (axis=1): [ 2.5  6.5 10.5]

Maximum element: 12
Maximum along columns (axis=0): [ 9 10 11 12]
Maximum along rows (axis=1): [ 4  8 12]


More on axis and shape and aggregation

In [44]:
arr = np.random.randint(1,10,(2,4,5))

print(arr.shape)

print(arr.sum(axis=0).shape)  # (4,5)
print(arr.sum(axis=1).shape)  # (2,5)
print(arr.sum(axis=2).shape)  # (2,4)

(2, 4, 5)
(4, 5)
(2, 5)
(2, 4)


In [34]:
# Define two 2D arrays
arr_a = np.array([[1, 2, 3],
                  [4, 5, 6]])
arr_b = np.array([[7, 8, 9],
                  [10, 11, 12]])

print('Original array A:\n', arr_a)
print('Original array B:\n', arr_b)

# Element-wise Sum
print('\nElement-wise sum of A and B:\n', arr_a + arr_b)

# Element-wise Multiplication
print('\nElement-wise multiplication of A and B:\n', arr_a * arr_b)

# Matrix Multiplication (dot product)
# Note: For matrix multiplication, the number of columns in the first array
# must equal the number of rows in the second array.
# Reshape arr_b to be compatible for dot product with arr_a (2x3 @ 3x2)
arr_b_reshaped = np.array([[7, 10],
                           [8, 11],
                           [9, 12]])
print('\nOriginal array A:\n', arr_a)
print('Reshaped array B for dot product:\n', arr_b_reshaped)
print('\nMatrix multiplication (dot product) of A and B_reshaped:\n', np.dot(arr_a, arr_b_reshaped))

Original array A:
 [[1 2 3]
 [4 5 6]]
Original array B:
 [[ 7  8  9]
 [10 11 12]]

Element-wise sum of A and B:
 [[ 8 10 12]
 [14 16 18]]

Element-wise multiplication of A and B:
 [[ 7 16 27]
 [40 55 72]]

Original array A:
 [[1 2 3]
 [4 5 6]]
Reshaped array B for dot product:
 [[ 7 10]
 [ 8 11]
 [ 9 12]]

Matrix multiplication (dot product) of A and B_reshaped:
 [[ 50  68]
 [122 167]]


Reshape and auto reshape

In [38]:
print('reshape 1D to 2D 12 = 3X4 ',np.ones(12).reshape(3,4))
print('auto reshape 2D to 3D', np.ones((3,4)).reshape(2,-1,2))

# can only mention one unknown for reshape
# print('auto reshape 2D to 3D', np.ones((3,4)).reshape(2,-1,1))

reshape 1D to 2D 12 = 3X4  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
auto reshape 2D to 3D [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


stack and concatenate

hstack means add arrays side by side

vstack means add arrays one after another

Axis 0 = vertical direction (increase rows for concatenation) == vstack

Axis 1 = horizontal direction (increase column for concataenation) == hstack

In [41]:
import numpy as np

# Define two 2D arrays for demonstration
arr_2d_1 = np.array([[1, 2, 3],
                     [4, 5, 6]])
arr_2d_2 = np.array([[7, 8, 9],
                     [10, 11, 12]])
arr_2d_3 = np.array([[13, 14],
                     [15, 16]])

print('Original Array 1:\n', arr_2d_1)
print('Original Array 2:\n', arr_2d_2)
print('Original Array 3:\n', arr_2d_3)

# hstack (horizontal stack) - concatenates arrays column-wise
# Arrays must have the same number of rows.
print('\n--- hstack (Horizontal Stack) ---')
print('hstack (arr_2d_1, arr_2d_2):\n', np.hstack((arr_2d_1, arr_2d_2)))

# vstack (vertical stack) - concatenates arrays row-wise
# Arrays must have the same number of columns.
print('\n--- vstack (Vertical Stack) ---')
print('vstack (arr_2d_1, arr_2d_2):\n', np.vstack((arr_2d_1, arr_2d_2)))

# concatenate - more general function, takes 'axis' argument
print('\n--- concatenate ---')

# Concatenate along axis=1 (columns) - equivalent to hstack
print('concatenate along axis=1 (columns, like hstack):\n', np.concatenate((arr_2d_1, arr_2d_2), axis=1))

# Concatenate along axis=0 (rows) - equivalent to vstack
print('concatenate along axis=0 (rows, like vstack):\n', np.concatenate((arr_2d_1, arr_2d_2), axis=0))

# Example with incompatible shapes for stacking (different rows for hstack, different cols for vstack)
# The following would raise an error:
# print('hstack (arr_2d_1, arr_2d_3):\n', np.hstack((arr_2d_1, arr_2d_3))) # Error: arrays must have same number of rows
# print('vstack (arr_2d_1, arr_2d_3):\n', np.vstack((arr_2d_1, arr_2d_3))) # Error: arrays must have same number of columns


Original Array 1:
 [[1 2 3]
 [4 5 6]]
Original Array 2:
 [[ 7  8  9]
 [10 11 12]]
Original Array 3:
 [[13 14]
 [15 16]]

--- hstack (Horizontal Stack) ---
hstack (arr_2d_1, arr_2d_2):
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

--- vstack (Vertical Stack) ---
vstack (arr_2d_1, arr_2d_2):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

--- concatenate ---
concatenate along axis=1 (columns, like hstack):
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
concatenate along axis=0 (rows, like vstack):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Image processing

In [50]:
image = np.random.randint(0, 255, (10, 10), dtype=np.uint8)
print(image)
print('--------image statistics------------')
print('min pixel value',np.min(image))
print('max pixel value',np.max(image))
print('Brightness or mean',np.mean(image))
print('Contrast or standard deviation',np.std(image))

[[130 210 182  46 149 120  42 157 164 219]
 [ 56  99 180 109 133 126  55 164 232   6]
 [222 152 178 159  28 249 133 148  26 132]
 [ 27 241  63 102  59 209  51  92 174  95]
 [ 81   6 142 210 240 126 162 145 155  25]
 [111  24 196  31 224 168 114 205  66 249]
 [192   1  39  33  43  66  53  39 144 178]
 [112 127 165 169 102 183 105   9 247 186]
 [174  53  89 232 214  20 127 154 129  92]
 [ 69  45 157 220 147 184 231 157   5  32]]
--------image statistics------------
min pixel value 1
max pixel value 249
Brightness or mean 125.23
Contrast or standard deviation 69.79238568783848


In [51]:
# argmax - returns the indices of the maximum values along an axis
print('Index of max pixel value (flattened image):', np.argmax(image))
print('Index of max pixel value along axis 0 (columns):', np.argmax(image, axis=0))
print('Index of max pixel value along axis 1 (rows):', np.argmax(image, axis=1))

# argmin - returns the indices of the minimum values along an axis
print('\nIndex of min pixel value (flattened image):', np.argmin(image))
print('Index of min pixel value along axis 0 (columns):', np.argmin(image, axis=0))
print('Index of min pixel value along axis 1 (rows):', np.argmin(image, axis=1))

# clip - limits the values in an array to a specified range
# Example: clip image values between 50 and 200
clipped_image = np.clip(image, 50, 200)
print('\nOriginal image min:', np.min(image), 'max:', np.max(image))
print('Clipped image (min=50, max=200) min:', np.min(clipped_image), 'max:', np.max(clipped_image))

Index of max pixel value (flattened image): 25
Index of max pixel value along axis 0 (columns): [2 3 5 8 4 2 9 5 7 5]
Index of max pixel value along axis 1 (rows): [9 8 5 1 4 9 0 8 3 6]

Index of min pixel value (flattened image): 61
Index of min pixel value along axis 0 (columns): [3 6 6 5 2 8 0 7 9 1]
Index of min pixel value along axis 1 (rows): [6 9 8 0 1 1 1 7 5 8]

Original image min: 1 max: 249
Clipped image (min=50, max=200) min: 50 max: 200
