<a href="https://colab.research.google.com/github/ritam-sarkar/python_libraries/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
python_list = [1,2,3]
print(python_list, type(python_list))
arr1 = np.array([1,2,3])
print(arr1, type(arr1))


[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


#### Vectorized operation no lopp needed

In [4]:
# print with lambda
print("add 10 with each x on python list",[x+10 for x in python_list])
print("vectorized add",arr1+10)
print("add in list with numpy",np.add(python_list,10))


add 10 with each x on python list [11, 12, 13]
vectorized add [11 12 13]
add in list with numpy [11 12 13]


Other methods of numpy

In [5]:
print('print zeroes', np.zeros(3))
print('print ones for 3X2 dimension', np.ones((3,2)))
print('arrange 0 to 10 with gap of 2', np.arange(0,10,2))
print('random value between 2 to 3', np.random.rand(2,3))

print zeroes [0. 0. 0.]
print ones for 3X2 dimension [[1. 1.]
 [1. 1.]
 [1. 1.]]
arrange 0 to 10 with gap of 2 [0 2 4 6 8]
random value between 2 to 3 [[0.7038283  0.87895881 0.11692295]
 [0.18823208 0.00662201 0.50436802]]


Type promotion




int → float → complex → object

In [6]:
arr_int = np.array([1, 2, 3])
arr_float = np.array([1.0, 2.0, 3.0])
arr_mixed = np.array([1, 2.5, 3])  # Mixed types → promoted to float
arr_mixed2 = np.array([1, "hello", 3])
print('promoted to float ',arr_mixed)
print('promoted to string object ',arr_mixed2)

promoted to float  [1.  2.5 3. ]
promoted to string object  ['1' 'hello' '3']


n dimension array properties

In [21]:
arr = np.ones((2,3,4))
print(arr)
print('shape',arr.shape)
print('shape',arr.size)
print('itemsize ',arr.itemsize) # memory per element is 8 bytes
print('total memory used ', arr.nbytes)
print('dimension ', arr.ndim)
print('Transpose', arr.T.shape)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
shape (2, 3, 4)
shape 24
itemsize  8
total memory used  192
dimension  3
Transpose (4, 3, 2)


Indexing and slicing 1D

In [28]:
# 1D Array Indexing
print('--- 1D Array Indexing ---')
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70])
print(f'Original 1D array: {arr_1d}')

# Positive Indexing
print(f'Element at index 0: {arr_1d[0]}')
print(f'Element at index 3: {arr_1d[3]}')

# Negative Indexing
print(f'Element at last index (-1): {arr_1d[-1]}')
print(f'Element at second to last index (-2): {arr_1d[-2]}')

# Slicing (Positive Indices)
print(f'Elements from index 1 to 4 (exclusive): {arr_1d[1:4]}')
print(f'Elements from beginning to index 3 (exclusive): {arr_1d[:3]}')
print(f'Elements from index 4 to end: {arr_1d[4:]}')

# Slicing (Negative Indices)
print(f'Elements from beginning to second to last (exclusive): {arr_1d[:-1]}')
print(f'Elements from third to last to end: {arr_1d[-3:]}')

# Slicing (Mixed Positive/Negative Indices)
print(f'Elements from index 1 to second to last (exclusive): {arr_1d[1:-1]}')
print(f'Elements from index 2 to third to last (exclusive): {arr_1d[2:-2]}')

# slicing with step
print(f'Elements from index 1 to 4 (exclusive) with step 2: {arr_1d[1:4:2]}') #[start : end exclusive : step ]

--- 1D Array Indexing ---
Original 1D array: [10 20 30 40 50 60 70]
Element at index 0: 10
Element at index 3: 40
Element at last index (-1): 70
Element at second to last index (-2): 60
Elements from index 1 to 4 (exclusive): [20 30 40]
Elements from beginning to index 3 (exclusive): [10 20 30]
Elements from index 4 to end: [50 60 70]
Elements from beginning to second to last (exclusive): [10 20 30 40 50 60]
Elements from third to last to end: [50 60 70]
Elements from index 1 to second to last (exclusive): [20 30 40 50 60]
Elements from index 2 to third to last (exclusive): [30 40 50]
Elements from index 1 to 4 (exclusive) with step 2: [20 40]


Indexing and slicing 2D

In [32]:

# 2D Array Indexing
print('\n--- 2D Array Indexing ---')
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print('Original 2D array:\n', arr_2d)

# Positive Indexing (row, column)
print(f'Element at (0, 0): {arr_2d[0, 0]}')
print(f'Element at (1, 2): {arr_2d[1, 2]}')

# Negative Indexing
print(f'Element at last row, last column (-1, -1): {arr_2d[-1, -1]}')
print(f'Element at first row, second to last column (0, -2): {arr_2d[0, -2]}')

# Slicing Rows
print(f'First row: {arr_2d[0, :]}')
print(f'First two rows:\n{arr_2d[:2, :]}')
print(f'Last row: {arr_2d[-1, :]}')

# Slicing Columns
print(f'First column: {arr_2d[:, 0]}')
print(f'Last two columns:\n{arr_2d[:, -2:]}')

# Slicing Both Rows and Columns (Positive Indices)
print(f'Subset (top-left 2x2):\n{arr_2d[0:2, 0:2]}')

# Slicing Both Rows and Columns (Negative Indices)
print(f'Subset (bottom-right 2x2, using negative slicing):\n{arr_2d[-2:, -2:]}')

# Slicing Both Rows and Columns (Mixed Indices)
print(f'Subset (first row, last two columns): {arr_2d[0, -2:]}')
print(f'Subset (all rows, first to second to last column):\n{arr_2d[:, 0:-1]}')

# Using boolean indexing for more advanced selection
print('\n--- Boolean Indexing (2D Array) ---')
print(f'Elements greater than 7:\n{arr_2d[arr_2d > 7]}')
print(f'Elements which are even: {arr_2d[arr_2d % 2 == 0]}')
# Boolean element genration
print(f'Generate same shape but boolean value:\n  {arr_2d > 25}')


--- 2D Array Indexing ---
Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at (0, 0): 1
Element at (1, 2): 7
Element at last row, last column (-1, -1): 12
Element at first row, second to last column (0, -2): 3
First row: [1 2 3 4]
First two rows:
[[1 2 3 4]
 [5 6 7 8]]
Last row: [ 9 10 11 12]
First column: [1 5 9]
Last two columns:
[[ 3  4]
 [ 7  8]
 [11 12]]
Subset (top-left 2x2):
[[1 2]
 [5 6]]
Subset (bottom-right 2x2, using negative slicing):
[[ 7  8]
 [11 12]]
Subset (first row, last two columns): [3 4]
Subset (all rows, first to second to last column):
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

--- Boolean Indexing (2D Array) ---
Elements greater than 7:
[ 8  9 10 11 12]
Elements which are even: [ 2  4  6  8 10 12]
Generate same shape but boolean value:
  [[False False False False]
 [False False False False]
 [False False False False]]


Vector operation

In [33]:
# Vector operations on a 2D array
print('--- Vector Operations on 2D Array ---')
print('Original 2D array:\n', arr_2d)

# Addition with a scalar
print('\nAddition with scalar (5):\n', arr_2d + 5)

# Multiplication with a scalar
print('\nMultiplication with scalar (2):\n', arr_2d * 2)

# Subtraction with a scalar
print('\nSubtraction with scalar (3):\n', arr_2d - 3)

# Element-wise multiplication with another array (must have same shape)
arr_2d_b = np.array([[1, 1, 1, 1],
                     [2, 2, 2, 2],
                     [3, 3, 3, 3]])
print('\nElement-wise multiplication with another array (arr_2d_b):\n', arr_2d * arr_2d_b)

# Sum of all elements
print('\nSum of all elements:', np.sum(arr_2d))

# Sum along an axis (axis=0 for columns, axis=1 for rows)
print('\nSum along columns (axis=0):', np.sum(arr_2d, axis=0))
print('Sum along rows (axis=1):', np.sum(arr_2d, axis=1))

# Mean of all elements
print('\nMean of all elements:', np.mean(arr_2d))

# Mean along an axis
print('Mean along columns (axis=0):', np.mean(arr_2d, axis=0))
print('Mean along rows (axis=1):', np.mean(arr_2d, axis=1))

# Maximum element
print('\nMaximum element:', np.max(arr_2d))

# Maximum element along an axis
print('Maximum along columns (axis=0):', np.max(arr_2d, axis=0))
print('Maximum along rows (axis=1):', np.max(arr_2d, axis=1))

--- Vector Operations on 2D Array ---
Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Addition with scalar (5):
 [[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]

Multiplication with scalar (2):
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction with scalar (3):
 [[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]

Element-wise multiplication with another array (arr_2d_b):
 [[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]

Sum of all elements: 78

Sum along columns (axis=0): [15 18 21 24]
Sum along rows (axis=1): [10 26 42]

Mean of all elements: 6.5
Mean along columns (axis=0): [5. 6. 7. 8.]
Mean along rows (axis=1): [ 2.5  6.5 10.5]

Maximum element: 12
Maximum along columns (axis=0): [ 9 10 11 12]
Maximum along rows (axis=1): [ 4  8 12]


In [34]:
# Define two 2D arrays
arr_a = np.array([[1, 2, 3],
                  [4, 5, 6]])
arr_b = np.array([[7, 8, 9],
                  [10, 11, 12]])

print('Original array A:\n', arr_a)
print('Original array B:\n', arr_b)

# Element-wise Sum
print('\nElement-wise sum of A and B:\n', arr_a + arr_b)

# Element-wise Multiplication
print('\nElement-wise multiplication of A and B:\n', arr_a * arr_b)

# Matrix Multiplication (dot product)
# Note: For matrix multiplication, the number of columns in the first array
# must equal the number of rows in the second array.
# Reshape arr_b to be compatible for dot product with arr_a (2x3 @ 3x2)
arr_b_reshaped = np.array([[7, 10],
                           [8, 11],
                           [9, 12]])
print('\nOriginal array A:\n', arr_a)
print('Reshaped array B for dot product:\n', arr_b_reshaped)
print('\nMatrix multiplication (dot product) of A and B_reshaped:\n', np.dot(arr_a, arr_b_reshaped))

Original array A:
 [[1 2 3]
 [4 5 6]]
Original array B:
 [[ 7  8  9]
 [10 11 12]]

Element-wise sum of A and B:
 [[ 8 10 12]
 [14 16 18]]

Element-wise multiplication of A and B:
 [[ 7 16 27]
 [40 55 72]]

Original array A:
 [[1 2 3]
 [4 5 6]]
Reshaped array B for dot product:
 [[ 7 10]
 [ 8 11]
 [ 9 12]]

Matrix multiplication (dot product) of A and B_reshaped:
 [[ 50  68]
 [122 167]]
